# 資料前處理(Label encoding、 One hot encoding)
這兩個編碼方式的目的是為了將類別 (categorical)或是文字(text)的資料轉換成數字，而讓程式能夠更好的去理解及運算。
> Label encoding : 把每個類別 mapping 到某個整數，不會增加新欄位

> One hot encoding : 為每個類別新增一個欄位，用 0/1 表示是否

![](images/Encoder.PNG)


## Encoding Categorical features (or label)
![](images/Encoding.PNG)

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'],
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
df

  blood     Y       Z
0     A  high     NaN
1     B   low     NaN
2    AB  high -1196.0
3     O   mid    72.0
4     B   mid    83.0

# 方法一：sklearn - label encoder + onehot encoder
>onehot encoder要用2D array，若維度所以要用reshape(-1,1)<br>
>onehot encoder要數字，若資料文文字要先用label encoder轉數字

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder() #讓這個工具(LabeEncoder)assign給變數(encoder)
encoded_Y = encoder.fit_transform(df['blood']) #把想要轉換的欄位(df['blood'])拿過來
print(encoded_Y)

df['blood'] = encoded_Y
df

[0 2 1 3 2]

   blood     Y       Z
0      0  high     NaN
1      2   low     NaN
2      1  high -1196.0
3      3   mid    72.0
4      2   mid    83.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder() #讓這個工具(OneHotEncoder)assign給變數(onehot)
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
print(type(df['blood']))     # <class 'pandas.core.series.Series'>

d = np.array(df['blood'])
print(type(d))          # <class 'numpy.ndarray'>
print(d.shape)          # (5,)
# print(d.reshape(-1, 1).shape)  # (5, 1)

# onehot_df = onehot.fit_transform(d.reshape(-1, 1))
# print(type(onehot_df))      # <class 'scipy.sparse._csr.csr_matrix'>

onehot_df = onehot.fit_transform(d.reshape(-1, 1)).toarray()
print(onehot_df)

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
(5,)
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

## One hot encoding
One Hot encoding的編碼邏輯為將類別拆成多個行(column)，每個列中的數值由1、0替代，當某一列的資料存在的該行的類別則顯示1，反則顯示0。

然在指定column進行編碼的情形下，One hot encoding<b>無法直接對字串進行編碼，必須先透過Label encoding將字串以數字取代後再進行One hot encoding處理。</b>

> categorical_features = [0]: 表示欲在data上執行One hot encoding的index為0

> data_le: 為經過Label encoding編碼的資料(註:OneHotEncoder的輸入要為2-D array，而Label encoding為1-D array)

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

[連結文字]OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
從結果可以知道，數字0的column 代表的是A、數字1的column 代表的是B，而數字2的column 代表的是AB。
除了轉換字串外，One hot encoding也可以轉換數字。在此處的data就不需要先經過Label encoding編碼

```python
# importing one hot encoder from sklearn
# There are changes in OneHotEncoder class
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
   
# creating one hot encoder object with categorical feature 0
# indicating the first column
columnTransformer = ColumnTransformer([('encoder',
                                        OneHotEncoder(),
                                        [0])],
                                      remainder='passthrough')
  
data = np.array(columnTransformer.fit_transform(data), dtype = str)
```

In [ ]:
# importing one hot encoder from sklearn
# There are changes in OneHotEncoder class
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# creating one hot encoder object with categorical feature 0
# indicating the first column
columnTransformer = ColumnTransformer([('encoder',
                                        OneHotEncoder(),
                                        [0])],
                                      remainder='passthrough')

df = pd.DataFrame({'blood':['A','B','AB','O','B'],
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
# <方式1>: 無法使用
# data = columnTransformer.fit_transform(df).toarray()   # AttributeError: 'numpy.ndarray' object has no attribute 'toarray'
   # debug看看，發現data本身就是array
# data = columnTransformer.fit_transform(df)
# print(type(data))                            # <class 'numpy.ndarray'>

# <方式2>:
data = np.array(columnTransformer.fit_transform(df), dtype = str)
data   # 為array
# array([['1.0', '0.0', '0.0', '0.0', 'high', 'nan'],
#        ['0.0', '0.0', '1.0', '0.0', 'low', 'nan'],
#        ['0.0', '1.0', '0.0', '0.0', 'high', '-1196.0'],
#        ['0.0', '0.0', '0.0', '1.0', 'mid', '72.0'],
#        ['0.0', '0.0', '1.0', '0.0', 'mid', '83.0']], dtype='<U7')

data_le = pd.DataFrame(data)
data_le

     0    1    2    3     4        5
0  1.0  0.0  0.0  0.0  high      nan
1  0.0  0.0  1.0  0.0   low      nan
2  0.0  1.0  0.0  0.0  high  -1196.0
3  0.0  0.0  0.0  1.0   mid     72.0
4  0.0  0.0  1.0  0.0   mid     83.0

# 方法二：Keras - label encoder + to_categorical
>to_categorical要數字，若資料文文字要先用label encoder轉數字

In [ ]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

df = pd.DataFrame({'blood':['A','B','AB','O','B'],
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
# step1: 文字先轉成數字
# label encoder

encoder = LabelEncoder() #讓這個工具(LabeEncoder)assign給變數(encoder)
encoded_Y = encoder.fit_transform(df['blood']) #把想要轉換的欄位(df['blood'])拿過來
print(encoded_Y)
df['blood'] = encoded_Y
df

# step2: 數字再轉成onehotencoding
# convert integers to one hot encoding
keras_onthot = np_utils.to_categorical(encoded_Y)
keras_onthot




# # ----------錯誤做法-------------------
# # step1: 文字先轉成數字
# # label encoder
# encoder = LabelEncoder() #讓這個工具(LabeEncoder)assign給變數(encoder)
# encoded_Y = encoder.fit_transform(df['blood']) #把想要轉換的欄位(df['blood'])拿過來

# # step2: 數字再轉成onehotencoding
# # convert integers to one hot encoding
# keras_onthot = np_utils.to_categorical(df['blood'])
# keras_onthot
# # 錯誤: ValueError: invalid literal for int() with base 10: 'A'
# # 它需要int()，而我們給了str

[0 2 1 3 2]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)

## 方法三：pd.get_dummies方法
![](images/Encoding_pd.PNG)
pd.get_dummies(df)
>get_dummies可以直接轉字串，反而無法轉換數字<br>
>get_dummies沒指定columns，會全部轉換

In [ ]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'],
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]})
df1 = pd.get_dummies(df)
print(df1)

df2 = pd.get_dummies(df.blood)
print(df2)

        Z  blood_A  blood_AB  blood_B  blood_O  Y_high  Y_low  Y_mid
0     NaN        1         0        0        0       1      0      0
1     NaN        0         0        1        0       0      1      0
2 -1196.0        0         1        0        0       1      0      0
3    72.0        0         0        0        1       0      0      1
4    83.0        0         0        1        0       0      0      1
   A  AB  B  O
0  1   0  0  0
1  0   0  1  0
2  0   1  0  0
3  0   0  0  1
4  0   0  1  0

## 練習一：sklearn - label encoder + onehot encoder
下面的資料可以看到country那欄皆為字串， 大部分的模型都是基於數學運算，字串無法套入數學模型進行運算，<br>
在此先對其進行Label encoding編碼，我們從 sklearn library中導入 LabelEncoder class，對第一行資料進行fit及transform並取代之。

In [48]:
import numpy as np
import pandas as pd
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

# 轉換country: pandas
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

    # step1: label encoder文字先轉成數字
encoder = LabelEncoder()
data['Country'] = encoder.fit_transform(data['Country'])
print(data)

np.array(data['Country']).reshape(-1, 1)

    # step2: 數字再轉成onehotencoding
onehot = OneHotEncoder()
result = onehot.fit_transform(np.array(data['Country']).reshape(-1, 1)).toarray()

    # step3: 資料處理及合併
result = pd.DataFrame(result)
data =  data.drop('Country', axis=1)
data = pd.concat([result, data], axis=1)
data

   Country  Age  Salary
0        2   25   20000
1        0   30   32000
2        1   45   59000
3        0   35   60000
4        1   22   43000
5        2   36   52000

     0    1    2  Age  Salary
0  0.0  0.0  1.0   25   20000
1  1.0  0.0  0.0   30   32000
2  0.0  1.0  0.0   45   59000
3  1.0  0.0  0.0   35   60000
4  0.0  1.0  0.0   22   43000
5  0.0  0.0  1.0   36   52000

## 練習二：Keras - label encoder + to_categorical

In [51]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

# 轉換country: array
    # step1: label encoder文字先轉成數字
encoder = LabelEncoder()
data['Country'] = encoder.fit_transform(data['Country'])

    # step2: 數字再轉成onehotencoding
keras_onthot = np_utils.to_categorical(data['Country'])
keras_onthot


    # step3: 資料處理及合併
keras_onthot = pd.DataFrame(keras_onthot)
data =  data.drop('Country', axis=1)
data = pd.concat([keras_onthot, data], axis=1)
data

     0    1    2  Age  Salary
0  0.0  0.0  1.0   25   20000
1  1.0  0.0  0.0   30   32000
2  0.0  1.0  0.0   45   59000
3  1.0  0.0  0.0   35   60000
4  0.0  1.0  0.0   22   43000
5  0.0  0.0  1.0   36   52000

## 練習三：Pandas.get_dummies
>　get_dummies : 僅能將字串轉換為One hot encoding表示形式， 沒指定columns會全部轉換。

In [55]:
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

# 轉換country: 全部欄位與部分欄位
df_all = pd.get_dummies(data)
print(df_all)

df_partial = pd.get_dummies(data.Country)
print(df_partial)

   Age  Salary  Country_Australia  Country_Ireland  Country_Taiwan
0   25   20000                  0                0               1
1   30   32000                  1                0               0
2   45   59000                  0                1               0
3   35   60000                  1                0               0
4   22   43000                  0                1               0
5   36   52000                  0                0               1
   Australia  Ireland  Taiwan
0          0        0       1
1          1        0       0
2          0        1       0
3          1        0       0
4          0        1       0
5          0        0       1